### ISSUE TITLE
Peer Review-Alan Montenegro

### ISSUE THREAD

**Issue by Alammonte** [tincho282/Mercado-Liebre-v2#1]
-[] 1 - Cumple (
Header: Si
Main: Si
Footer: Si )
-[] 2 - Cumple ( Esta bien, los 2em estan pasados a px, y faltaria el margen de 10 px)
-[] 3 - Cumple ( Cumple con todas las resoluciones )
-[] 4 - No cumple (Falta formulario )
-[] 5 - No cumple (Falta formulario )
-[] 7 - No cumple ( Falta formularios)
-[] 8 - No cumple ( Falta transicones y animaciones)
-[] 9 - (Tiene un buen pocisionamiento y esta muy bien echo para mejorar lo que falta)
-[] 10 - (Podría agregar los formularios e ir haciendo las transiciones)

**Comment by tincho282** [comment]
Se resolvieron los inconvenientes reportados del sitio.
